########################################
resolver: lts-11.17                    # i.e. ghc-8.2

allow-newer: true 

# nix:
#   enable:   true 
#   packages:
#   - zlib

########################################
# flags:

########################################
packages:

- workflow-types/
- workflow-extra/
- workflow-pure/

# - workflow

# - location:
#     ../spiros
#   extra-dep: true
#   subdirs: [.]
# - location:			
#     ../enumerate
#   extra-dep: true
#   subdirs: 
#   - enumerate 
#   - enumerate-function 
########################################
extra-deps:

- c-storable-deriving-0.1.3

- spiros-0.2
- enumerate-0.2.2

# - frisby-0.2.2
########################################