resolver: lts-7.14
compiler: ghc-8.0

nix:
  enable: true
  pure: false
  # or impure, so that xdg-open can open the default browser in a user's environment
  packages:
  - zlib
  - xdotool
  - xclip
  - xdg_utils
  - xorg.xprop
  # - xorg.xwininfo
  # shell-file: shell.nix

packages:
- .
- ../spiros
- ../workflow-types

extra-deps:
- spiros-0.0.0
- workflow-types-0.0.0
- process-1.4.3.0
